# Generated by Django 3.2.2 on 2021-05-06 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nwucaf.helpers.image_helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_name', models.CharField(choices=[('KD', 'Kgosi Dick'), ('MB', 'Mbada'), ('KH', 'Khayelitsha'), ('HV', 'Hopeville'), ('SP', 'Sol Plat'), ('JM', 'James'), ('M', 'Modiri'), ('N', 'Nkandla'), ('S', 'Sedibeng'), ('PG', 'Post Grad'), ('LC', 'Lost City')], max_length=2)),
                ('block_number', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=4)),
                ('student_number', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=10)),
                ('default', models.BooleanField(default=False)),
                ('address_type', models.CharField(choices=[('B', 'billing'), ('S', 'shipping'), ('C', 'cash')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RI', 'Rice'), ('CH', 'Chips'), ('DR', 'Drinks'), ('PA', 'Pap'), ('BR', 'Bread'), ('BI', 'Biscuit'), ('BE', 'Beef'), ('CK', 'Chicken'), ('CL', 'Chocolate')], max_length=2)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VoucherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('loaded_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pf', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_gross', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_fee', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_net', models.CharField(blank=True, max_length=20, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_option', models.CharField(choices=[('Card', 'Card Payment'), ('Voucher', 'PurpleCAF Voucher')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('delivery_option', models.CharField(blank=True, choices=[('RD', 'Residence Delivery + R10'), ('PU', 'Pick Up At Cafeteria + R5')], max_length=2, null=True)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('student_number', models.CharField(blank=True, max_length=8, null=True)),
                ('service_charge', models.IntegerField(default=0)),
                ('item', models.ManyToManyField(to='core.OrderItem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=nwucaf.helpers.image_helper.get_upload_path, verbose_name='Item image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
