# Generated by Django 2.2 on 2020-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200427_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('RI', 'Rice'), ('CH', 'Chips'), ('DR', 'Drinks'), ('PA', 'Pap'), ('BR', 'Bread'), ('BI', 'Biscuit'), ('BE', 'Beef'), ('CK', 'Chicken'), ('CL', 'Chocolate')], max_length=2),
        ),
    ]
