# Generated by Django 2.2 on 2020-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'billing'), ('S', 'shipping'), ('C', 'cash')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='block_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='room_number',
            field=models.CharField(max_length=4),
        ),
    ]
