# Generated by Django 2.2 on 2020-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200501_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('RD', 'Residence Delivery'), ('PU', 'Pick Up At Cafeteria')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Card', 'Card Payment'), ('Cash', 'Cash On Delivery')], max_length=5),
        ),
    ]
