# Generated by Django 2.2 on 2020-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200507_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('RD', 'Residence Delivery + R10'), ('PU', 'Pick Up At Cafeteria + R5')], max_length=2, null=True),
        ),
    ]
