# Generated by Django 2.2 on 2020-05-24 12:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20200524_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoucherBalance',
            new_name='VoucherAccount',
        ),
    ]
