# Generated by Django 2.2 on 2020-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200524_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Card', 'Card Payment'), ('Voucher', 'PurpleCAF Voucher')], max_length=8),
        ),
    ]
