# Generated by Django 2.2.12 on 2020-06-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_voucherlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherlog',
            old_name='user',
            new_name='staff',
        ),
    ]
